### PR TITLE
St feature folder structure

### PR DESCRIPTION
**Pull request by saveentoor**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please use png files not svg. Please make the changes.

**Comment by siddharthparmar7** [comment]
Your dir names should not have any black spaces. Please use the conventions we know to name dirs and files. Find out if you need all the images from Invision or you can use icon libraries instead of those images?

**Comment by siddharthparmar7** [comment]
Connect appropriate issue with your pull request and provide details of an assignee, labels and milestone. Thank you.

**Review by teelau — DISMISSED** [review]

**Review by teelau — DISMISSED** [review]

**Review by teelau — DISMISSED** [review]

**Review by teelau — DISMISSED** [review]

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
All the files related to react native should be in the client dir. Please move all the config files from your project root to the client dir.

**Comment by siddharthparmar7** [comment]
Run your project in the simulator to check if the changes are working before making a pull request. Thank you.

**Review by teelau — APPROVED** [review]

**Review by siddharthparmar7 — APPROVED** [review]

**Pull request merged**
