### PR TITLE
St feature folder structure

### PR DESCRIPTION
**Pull request by saveentoor**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Use imperative commit messages and your README file should not be in this feature branch. Please make the changes. Thank you.

**Comment by siddharthparmar7** [comment]
Please resolve merge conflicts for this branch.

**Review by siddharthparmar7 — COMMENTED** [review]
Your screens are missing container files. Please add container file for all of your screens. Thank you.

**Review by teelau — APPROVED** [review]
Changes look good now!

**Review by teelau — APPROVED** [review]
project structure is fine

**Review by siddharthparmar7 — COMMENTED** [review]
components dir should not have an index.js file hanging out by itself.

**Review by siddharthparmar7 — APPROVED** [review]

**Pull request merged**
